config/routes.rb
Lilyraid::Application.routes.draw do
  resources :lists
  resource :calendar
  resources :characters
  resources :accounts do
    member do
      post :add_to_list
      post :remove_from_list
    end

    resources :characters do
      member do
        get :roles
      end
    end
  end

  resources :raids do
    member do
      post :finalize
    end

    resources :signups do
      member do
        post :preferred
      end
    end

    resources :accounts do
      resources :raider_tags
    end

    resources :loots
    resources :locations
    resources :slots do
      collection do
        put :wait_list
      end
    end
  end

  namespace :admin do
    resources :characters
    resources :templates
    resources :instances
    resources :accounts do
      collection do
        post :rename
      end
    end
    resources :tags
    resources :guilds
  end

  match 'wowhead/:search' => 'loots#search', :as => 'wowhead'
  match 'roles/:id' => 'characters#roles'

  match 'login' => 'login#index', :as => 'login', :via => :get
  match 'login' => 'login#create', :as => 'login_post', :via => :post
  match 'logout' => 'login#logout', :as => 'logout', :via => :get

  root :to => 'raids#index'
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :list_positions, :dependent => :destroy, :order => :position
  has_many :accounts, :through => :list_positions
  has_one :loot

  def to_s
    self.name
  end

  def self.get_list(name)
    List.includes({ :list_positions => { :account => { :characters => :cclass } } }).where('lists.name = ? and date is null', name).order('list_positions.position').first
  end

  def self.get_list_from_raid(name, raid)
    List.includes({ :list_positions => {
                      :account => {
                        :characters => [:cclass,
                                        { :signups => {
                                            :slot => :raid }}]}}}).
      where('lists.name = ? and lists.date is null and raids.id = ?', name, raid.id).
      order('list_positions.position').first
  end

  def cclasses
    list_positions.map do |lp|
      lp.account.characters[0].cclass
    end.uniq.sort
  end

  # Returns the live version of this list
  def newest
    List.where('date is null and name = ?', self.name).first
  end

  # Helper function for console viewing :)
  def output
    self.list_positions.map do |lp|
      "#{lp.position}: #{lp.character}"
    end.join "\n"
  end

  # Returns the list position with a character, or nil if one doesn't exist
  def find(account)
    self.list_positions.where('account_id = ?', account.id).first
  end

  # Find all lists linked to this one, ordered by date
  def history
    List.where('date is not null and name = ?', self.name).order('date desc')
  end

  def raid_history(raid)
    List.where('date is not null and name = ? and raid_id = ?', self.name, raid.id).order('date desc')
  end

  # Grab only the notes from the history (With dates)
  def notes
    self.history.map { |list| "#{list.date.to_s(:raid)}: #{list.note}" }
  end

  # Takes a character that got loot and a list of characters that were present
  def new_loot(raid, loot)
    account_lp = self.list_positions.for_account(loot.character.account).first
    slot = raid.signups.seated.includes(:slot).where(:character_id => loot.character).slot

    if account_lp
      position = account_lp.position

      self.list_positions.where('account_id in (?) and position > ?',
                                raid.slots.in_term(slot.team).includes(:signup => {:character => :account}).all.
                                map(&:signup).compact.map(&:character).map(&:account).map(&:id),
                                position).order('position').all.each do |lp|
        temp = lp.position
        lp.position = position
        lp.save
        position = temp
      end

      account_lp.position = position
      account_lp.save

      self.reload
    end
  end

  # Adds character to end of list (don't do anything if character is already in list)
  def add_to_end(account)
    if !self.find(account)
      lp = ListPosition.new
      lp.list = self
      lp.account = account

      if self.list_positions.size == 0
        lp.position = 1
      else
        lp.position = self.list_positions.maximum("position") + 1
      end

      lp.save

      self.list_positions = ListPosition.where('list_id = ?', self.id).all

      lp
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter(:load_list, :only => [:show, :edit, :update])

  def index
    authorize! :read, List
    @lists = List.all
    @list = List.new
  end

  def show
    authorize! :read, @list
  end

  def edit
    authorize! :update, @list
  end

  def update
    authorize! :update, @list

    if @list.update_attributes(params[:list])
      redirect_to lists_path
    else
      render :edit
    end
  end

  def create
    authorize! :create, List

    @list = List.new(params[:list])
    if @list.save
      redirect_to lists_path
    else
      @lists = List.all
      render :index
    end
  end

  private

  def load_list
    @list = List.find(params[:id])
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.slim
- if list.new_record?
  h1 New Loot List
- else
  h1 Edit Loot List
= simple_form_for(list) do |f|
  = f.input :name
  = f.input :note, :input_html => { :rows => 4 }
  - unless current_user.officer_of.empty?
    = f.input :guild, :collection => (admin? ? Guild.cache : current_user.officer_of), :value_method => :name
  .submit
    = f.submit 'Save'

app/views/lists/_history.html.slim
- list = history
tr
  td
    div
      = list.note
      div.note
        = render(:partial => "shared/loot", :object => list.loot) if list.loot
        = "<br />" if list.loot
        - list.list_positions.each do |lp|
          - if @current_account == lp.account
            = content_tag(:b, "#{lp.position} #{lp.account.name}")
          - else
            | #{lp.position} #{lp.account.name}
            br
          = list.date.to_s

app/views/lists/_list.html.slim
div.list
  h3 = list.name
  dl
    - list.list_positions.each do |lp|
      dt
        = link_to(lp.account.name, account_url(lp.account))
        = lp.position
      - lp.account.characters.each do |character|
        dd
          = link_to(render(:partial => "shared/character", :object => character), "#{account_url(lp.account)}#character_#{character.id}")
      - if @current_account.admin
        dd
          = link_to("Remove", remove_from_list_account_url(lp.account), \
                    :confirm => 'Are you sure you want to remove this person from the loot list?', \
                    :method => :post, :class => 'tiny')

app/views/lists/_position.html.slim
tr
  td
    = link_to(if @current_account == position.account \
                content_tag(:b, "#{position.position} #{position.account.name}") \
              else \
                "#{position.position} #{position.account.name}" \
              end, \
              account_url(position.account))
  - position.account.active_characters.each do |character|
    td
      = link_to(render(:partial => "shared/character", :object => character), "#{account_url(position.account)}##{dom_id(character)}")

app/views/lists/edit.html.slim
= render :partial => 'lists/form', :locals => { :list => @list }

app/views/lists/index.html.slim
h1 Loot Lists
.lists
  - @lists.each do |list|
    .list
      .guild = guild_icon(Guild.named(list.guild))
      .name = link_to list.name, list_path(list)
      .note = list.note
      .actions
        ul
          - if can? :update, list
            li = link_to 'Edit', edit_list_path(list)
          - if can? :destroy, list
            li = link_to 'Delete', list, :confirm => 'Are you sure?', :method => :delete
- if can? :create, List
  = render :partial => 'lists/form', :locals => { :list => @list }

app/views/lists/show.html.slim
.list
  h1 = @list.name
  .guild = guild_icon(Guild.named(@list.guild))
  dl.positions
    dt.header Position
    dd.header Account
    - @list.list_positions.each do |lp|
      dt = lp.position
      dd = link_to(lp.account.name, account_url(lp.account))