config/routes.rb
Lilyraid::Application.routes.draw do
  resources :lists
  resource :calendar
  resources :characters
  resources :accounts do
    member do
      post :add_to_list
      post :remove_from_list
    end

    resources :characters do
      member do
        get :roles
      end
    end
  end

  resources :raids do
    member do
      post :finalize
    end

    resources :signups do
      member do
        post :preferred
      end
    end

    resources :accounts do
      resources :raider_tags
    end

    resources :loots
    resources :locations
    resources :slots do
      collection do
        put :wait_list
      end
    end
  end

  namespace :admin do
    resources :characters
    resources :templates
    resources :instances
    resources :accounts do
      collection do
        post :rename
      end
    end
    resources :tags
    resources :guilds
  end

  match 'wowhead/:search' => 'loots#search', :as => 'wowhead'
  match 'roles/:id' => 'characters#roles'

  match 'login' => 'login#index', :as => 'login', :via => :get
  match 'login' => 'login#create', :as => 'login_post', :via => :post
  match 'logout' => 'login#logout', :as => 'logout', :via => :get

  root :to => 'raids#index'
end

app/models/raid.rb
class Raid < ActiveRecord::Base
  belongs_to :account
  belongs_to :instance
  belongs_to :list

  has_many :raider_tags
  has_many :tags, :through => :raider_tags

  has_many :locations
  accepts_nested_attributes_for(:locations, :allow_destroy => true,
                                :reject_if => proc { |attr|
                                  attr['instance_id'].blank?
                                })
  has_many :instances, :through => :locations
  has_many :loots, :through => :locations

  before_save :apply_number_of_slots

  has_many :slots, :dependent => :destroy

  has_many :signups, :dependent => :destroy
  has_many :characters, :through => :signups

  has_many :logs

  scope :past, lambda { where('raids.date < ?', Date.today) }
  scope :last_month, lambda { where('raids.date >= ?', Date.today - 1.month) }
  scope :last_three_months, lambda { where('raids.date >= ?', Date.today - 3.months) }
  scope :in_instance, lambda { |instance| where(:instance_id => instance) }

  Inf = 1/0.0

  def to_s
    self.name
  end

  # Validation
  validates_presence_of :name

  def started?
    Time.now > self.date
  end

  def number_of_slots
    self.slots.size || 10
  end

  def number_of_slots=(num)
    @number_of_slots = case num
                       when String
                         num.to_i
                       else
                         num
                       end
  end

  def date=(date)
    case date
    when String
      write_attribute(:date, Time.parse(date))
    else
      write_attribute(:date, date)
    end
  end        

  def confirmed_characters
    slots.map do |slot|
      if slot.signup
        slot.signup.character
      end
    end.compact
  end

  def accounts
    slots.map do |slot|
      if slot.signup
        slot.signup.character.account
      end
    end.compact
  end

  def character_in_raid(character)
    confirmed_characters.member?(character)
  end

  def waiting_list_by_account
    waiting_list.inject([]) do |list, signup|
      if list.empty?
        [[signup]]
      elsif list.last.first.character.account_id == signup.character.account_id
        list.last << signup
        list
      else
        list << [signup]
      end
    end
  end

  def is_open
    return true

    slots.each do |slot|
      if !slot.closed
        return true
      end
    end

    return false
  end

  def signups_from(account)
    signups.select do |signup|
      signup.character.account == account
    end
  end

  def remove_character(char)
    # Delete the signup_slot_types and signup row
    signup = self.signups.where(:character_id => char).first

    if signup
      date = signup.date
      # Destroy signups, this opens the slots up as well
      Signup.destroy(signup.id)

      # Redo the raid if raid
      resignup(date) unless locked

      return true
    else
      return false
    end
  end

  def find_character(char)
    self.slots.includes(:signup).where(:character_id => char).first
  end

  def resignup(date)
    signups = Signup.where('date >= ?', date).all

    # Delete all slots that are tied to signsup past this date
    signups.each do |signup|
      signup.clear_slots
    end

    # redo all signups that occur on or past this date
    signups.each do |signup|
      place_character(signup)
    end
  end

  def waiting_list
    accounts = slots.map { |slot| slot.signup }.compact.map { |signup| signup.character.account }

    signups.select do |signup|
      !accounts.member?(signup.character.account)
    end
  end

  def place_character(signup)
    self.slots.where('signup_id is null and closed = ?', false).order('cclass_id desc, slot_type_id desc').all.each do |slot|
      if slot.accept_char(signup)
        # This slow will accept this character
        slot.signup = signup
        slot.save
        break;
      end
    end
  end

  def add_waiting_list
    waiting_list.each do |signup|
      place_character(signup)
    end
  end

  def groups
    slots.each_slice(5)
  end

  def can_be_deleted?
    loots.size == 0
  end

  # Used for templates
  def template_id=(template_id)
    return if template_id.blank?

    # Number of slots that this raid has
    number_in_raid = self.slots.count

    # Apply a raid template to this raid
    template = Template.find(template_id)
    number_in_template = template.slots.count

    # Remove some slots from this raid
    self.slots.all[number_in_template..-1].map(&:destroy) if number_in_template < number_in_raid

    template.slots.each_with_index do |slot, index|
      if index < number_in_raid
        raid_slot = self.slots[index]

        # We only care if these slots are different
        if raid_slot != slot
          signup = raid_slot.signup
          raid_slot.update_attributes(slot.attributes)
          raid_slot.raid = self
          raid_slot.template = nil

          # Remove character if there is one that doesn't fit into the template
          if signup and raid_slot.accept(signup)
            raid_slot.signup = signup
          end
        end
      else
        # Easy, just create the new one
        self.slots.build(slot.attributes).template = nil
      end
    end
  end

  def uid
    "raid_#{self.id}@raids.dota-guild.com"
  end

  def word_date
    days = self.date.to_date - Date.today

    case days
    when -Inf..-1
      "In the past"
    when 0
      "Today"
    when 1
      "Tomorrow"
    when 2..days_left_in_week
      "This #{day_name(self.date)}"
    when (days_left_in_week + 1)..(days_left_in_week + 7)
      "Next #{day_name(self.date)}"
    when (days_left_in_week + 8)..days_left_in_month
      "Later this month"
    when (days_left_in_month + 1)..days_left_in_two_months
      "Next month"
    when (days_left_in_two_months + 1)..days_left_in_year
      "Later this year"
    else
      "In the future"
    end
  end

  private

  def day_name(date)
    date.strftime("%A")
  end

  def days_left_in_week
    Date.today.end_of_week - Date.today
  end

  def days_left_in_month
    Date.today.end_of_month - Date.today
  end

  def days_left_in_two_months
    (Date.today + 1.month).end_of_month - Date.today
  end

  def days_left_in_year
    Date.today.end_of_year - Date.today
  end

  def apply_number_of_slots
    # If we have a number of slots set, then apply them
    if @number_of_slots

      # Get the current number of slots
      number_in_raid = self.slots.count

      self.slots.all[@number_of_slots..-1].map(&:destroy) if @number_of_slots < number_in_raid

      (@number_of_slots - number_in_raid).times do
        self.slots.build(:roles => Role::ALL)
      end
    end
  end
end

app/controllers/raids_controller.rb
class RaidsController < ApplicationController
  before_filter(:load_raid, :only => [:edit, :update, :destroy, :show, :finalize])

  def index
    authorize! :read, Raid
    @old = params[:old]

    if @old
      @raids = Raid.where('raids.date < ?', Time.zone.now - 5.hours).order('raids.date desc')
    else
      @raids = Raid.where('raids.date >= ?', Time.zone.now - 5.hours).order('raids.date')
    end
  end

  def show
    authorize! :read, @raid
    @characters = @current_account.characters.active.not_signed_up_for(@raid)
    @tags = Tag.all
    @recent_raids = Raid.where('date < ?', @raid.date).limit(8).order('date desc').all.reverse
  end

  def finalize
    if @current_account == @raid.account or @current_account.admin
      @raid.finalized = !@raid.finalized
      @raid.save
    end

    finalize_log(@raid)

    respond_to do |format|
      format.html { redirect_to raid_url(@raid) }
    end
  end

  def edit
    authorize! :update, @raid
  end

  def update
    authorize! :update, @raid
    @raid.update_attributes(params[:raid])

    if @raid.save
      redirect_to raid_url(@raid)
    else
      flash[:error] = "Error saving raid"
      render :action => :edit
    end
  end

  def destroy
    if @current_account.can_edit?(@raid)
      @raid.destroy

      respond_to do |format|
        format.html { redirect_to raids_url }
        format.js { render :layout => false }
      end
    else
      flash[:error] = "You don't have permission to delete that raid"
      respond_to do |format|
        format.html { redirect_to raids_url }
        format.js { redirect_to raids_url }
      end
    end
  end

  def new
    authorize! :create, Raid
    @raid = Raid.new
    @raid.date = Time.zone.parse("Tomorrow 18h30") unless @raid.date
    @raid.number_of_slots = 10
  end

  def create
    authorize! :create, Raid

    # Create raid object
    @raid = Raid.new(params[:raid])
    @raid.account = current_user

    if @raid.save
      flash[:notice] = 'Raid saved!'
      redirect_to raid_url(@raid)
    else
      render :action => 'new'
    end
  end

  private

  def load_raid
    @raid = Raid.find(params[:id])
  end
end

app/helpers/raids_helper.rb
module RaidsHelper
  def raid_icon(raid)
    if raid.guild.present?
      guild_icon(Guild.named(raid.guild))
    else
      "&nbsp;".html_safe
    end
  end

  def slots(raid)
    raid.slots.map do |slot|
      if slot.signup
        "make_slot('#slot_#{slot.id}', '#{slot.accepts}');"
      end
    end.compact.join
  end
end

app/views/raids/_form.html.slim
div.raid id=dom_id(raid)
  - if raid.new_record?
    h1 New Raid
  - else
    h1 Edit Raid
  = simple_form_for raid do |f|
    = f.input :name
    = f.input :date, :as => :string, :input_html => { :class => 'lilydate' }
    = f.input :number_of_slots, :collection => (1..8).map{|n|n*5}
    - unless current_user.officer_of.empty?
      = f.input :guild, :collection => current_user.officer_of
    = f.input :list_id, :collection => List.order(:name).all, :include_blank => 'No Loot List'
    = f.association :instances, :as => :check_boxes, :collection => Instance.active.all, :label => 'Instance'
    = f.input :loot_note, :as => :text, :input_html => { :rows => 4}
    = f.input :note, :as => :text, :input_html => { :rows => 4}
    .submit
      = f.submit 'Save'

app/views/raids/_list.html.slim
.wrapper
  h3 = raid.list
  ul
    - raid.list.list_positions.in_raid(raid).each do |position|
      = render :partial => 'position', :locals => { :position => position, :raid => raid }
      li.empty class=('seated' if raid.list.list_positions.seated_in(raid).empty?) Empty

app/views/raids/_loots.html.haml
%dt Item History
- if loots.empty?
  %dd.empty None
- else
  = render :partial => 'shared/loot', :collection => loots

app/views/raids/_loots.html.slim
dt Item History
- if loots.empty?
  dd.empty None
- else
  = render :partial => 'shared/loot', :collection => loots

app/views/raids/_new_loot.html.slim
= form_for [raid, Loot.new(:item_url => 'URL', :item_name => 'Name')] do |f|
  div = f.collection_select :character_id, raid.characters.in_loot_list.seated_in(raid), :id, :name_with_account
  div = f.collection_select :location_id, raid.locations, :id, :name
  div = f.text_field :item_url, :class => 'dim', :onfocus => "field_focus(this);", :onblur => "field_blur(this);"
  div = f.text_field :item_name, :class => 'dim', :onfocus => "field_focus(this);", :onblur => "field_blur(this);"
  div = submit_tag('Save', :id => 'loot_submit')

app/views/raids/_position.html.slim
- hide ||= false
- position.account.characters.each do |character|
  = content_tag_for(:dd, character,
                    :class => "account_#{position.account.id} " + ((character.signups.in_raid(raid).first && character.signups.in_raid(raid).first.slot && (!hide)) ? 'seated' : '')) do
    = position.position
    = render :partial => "shared/character", :object => character
    span.team = character.signups.in_raid(raid).first.slot.team if character.signups.in_raid(raid).first.slot && character.signups.in_raid(raid).first.slot.team > 1
    .note = render :partial => 'signups/note', :object => character.signups.in_raid(raid).first

app/views/raids/_raid.html.slim
.raid id=dom_id(raid)
  .icon = raid_icon(raid)
  .name = link_to raid, raid
  .date
    = raid.date.to_s(:raid) if raid.date
    span = raid.word_date
  .instances
    ul
      - raid.locations.each do |location|
        li = location
  .finalized = raid.finalized? ? 'Yes' : 'No'
  .signups = render :partial => 'raids/signup', :collection => raid.signups_from(@current_account), :spacer_template => 'raids/signup_spacer'
  .actions
    ul
      - if can? :update, raid
        li = link_to 'Edit', edit_raid_path(raid)
      - if raid.can_be_deleted? and can? :destroy, raid
        li = link_to 'Delete', raid, :confirm => "Are you sure you want to delete #{raid}?", :method => :delete

app/views/raids/_signup.html.haml
= render :partial => 'shared/character', :object => signup.character
- if signup.in_raid_slot? and signup.raid.finalized?
  %b (Seated)

app/views/raids/_signup.html.slim
.signup class=signup_classes(signup)
  .avatar
    = image_tag character_image_url(signup.character)
    .icons
      .bg
    .guild
      = guild_icon(Guild.named(signup.character.guild))
  .actions
    ul
      li = link_to 'Edit', edit_raid_signup_path(signup.raid, signup)
      li = link_to 'Delete', raid_signup_path(signup.raid, signup), :method => :delete, :confirm => 'You sure you want to delete this signup?'

app/views/raids/_slot.html.slim
- if slot.signup
  = content_tag_for :li, slot, :class => slot.signup.classes do
    = render :partial => 'shared/character', :object => slot.signup.character
    = '*' if slot.signup.has_other_signups?
    .note = render :partial => 'slots/note', :locals => { :slot => slot }
- else
  = content_tag_for :li, slot do
    = render :partial => 'shared/slot', :object => slot
    - if slot.team > 1
      span.team = slot.team
    .note
      | Drag a character here from another slot or the waiting list to seat them
      | here. Only characters allowed into this slow will be able to be dropped
      | here.

app/views/raids/destroy.js.erb
$('#raid_<%= @raid.id %>').fadeOut();

app/views/raids/edit.html.slim
= render :partial => 'form', :locals => { :raid => @raid }

app/views/raids/index.html.slim
#raids
  h1 Raids
  table
    thead
      tr
        th Name
        th Date
        th Instances
        th Finalized?
        th Your Signups
    tbody
      - @raids.each do |raid|
        tr id="raid_#{raid.id}"
          td
            = link_to raid, raid
            = raid_icon(raid)
          td
            = raid.date.to_s(:raid) if raid.date
            span.note = raid.word_date
          td
            ul
              - raid.locations.each do |location|
                li = location
          td = raid.finalized? ? 'Yes' : 'No'
          td
            / = render :partial => 'raids/signup', :collection => raid.signups_from(@current_account), :spacer_template => 'raids/signup_spacer'

app/views/raids/show.html.slim
.raid id=dom_id(@raid)
  h1 = @raid.name
  .guild
    - if @raid.guild.present?
      = guild_icon(Guild.named(@raid.guild))
  .data
    .info
      ul.actions
        - if can? :update, @raid
          li = link_to 'Edit', edit_raid_path(@raid)
          li = link_to (@raid.finalized? ? 'Un-Finalize' : 'Finalize'), finalize_raid_url(@raid), :method => :post, :confirm => "Are you sure you want to #{@raid.finalized? ? 'un-finalize' : 'finalize'} this raid?"
        - if can? :destroy, @raid
          li = link_to 'Delete', @raid, :confirm => "Are you sure you want to delete #{@raid}?", :method => :delete
      dl
        dt Date:
        dd = @raid.date.to_s(:raid)
        - unless @raid.locations.empty?
          dt Instances:
          dd
            ul
              - @raid.locations.each do |location|
                li = location.instance
        dt Created By:
        dd = @raid.account
        - if @raid.loot_note.present?
          dt Loot rules:
          dd = @raid.loot_note
        - if @raid.note.present?
          dt Note:
          dd = @raid.note
    .your_signups
      h2 Your Signups
      - if @raid.signups.from_account(current_account).empty?
        p.no_signups None
      - else
        .signups
          - @raid.signups.from_account(current_account).each do |signup|
            = render :partial => 'signup', :object => signup
      - unless @raid.started? or @characters.empty?
        h2 Add Signup
        = simple_form_for [@raid, Signup.new] do |f|
          = f.input :character_id, :collection => @characters, :include_blank => false
          = f.input :note, :placeholder => 'Note'
          = submit_tag 'Add Signup'
          = f.input :roles, :collection => Role.all.map {|r| [t("role.#{r}"), r]}, :as => :check_boxes
  - if (can? :edit, @raid) || @raid.finalized?
    .slots
      h2 Slots
      .left
        .waiting_list = render :partial => 'waiting_list', :object => @raid.signups
      .seated
        .groups
          - @raid.slots.each_slice(5) do |group|
            = render :partial => 'group', :object => group
  - if @raid.list
    .loot
      h2 Loot
      .left
        .list = render :partial => 'list', :locals => {:raid => @raid}
        - if admin?
          .add
            .wrapper
              h3 Add to Loot List
              ul
                - @raid.signups.not_in_loot_list.each do |signup|
                  li = link_to(render(:partial => "shared/character", :object => signup.character), add_to_list_account_url(signup.character.account), :onclick => "if(confirm('Are you sure you want to add #{signup.character.account.name} to the loot list?')) { $.post('#{add_to_list_account_url(signup.character.account)}', { raid_id: '#{@raid.id}', authenticity_token: AUTH_TOKEN }, null, 'script'); } return false;")
      .items = render :partial => 'loots', :object => @raid.loots
      - if can?(:edit, @raid) and @raid.list
        .new
          h3 New Loot
          = render :partial => 'shared/wowhead'
          - @raid.locations.each do |location|
            dt #{location.instance.name} Loot
            dd
              = select_tag 'instance_loot', "<option value=\"\"></option>" + options_for_select(location.instance.loots.all(:order => "loots.item_name").map { |loot| [loot.item_name, loot.item_url] }.uniq), :onchange => "fill_loot_with_location($(this).find(':selected').text(), this.value, '#{location.id}');"
          /- unless Character.not_signed_up_for(@raid).empty?
            dt Add Signup:
            dd#admin_new_signup
              = form_for [@raid, Signup.new(:note => 'Note')] do |f|
                div
                  = f.collection_select :character_id, Character.not_signed_up_for(@raid), :id, :name_with_level_and_account, {}, :onchange => "character_roles(this, '#admin_new_signup_roles');"
                  = f.text_field :note, :onfocus => "field_focus(this);", :onblur => "field_blur(this);", :class => 'dim'
                  = submit_tag 'Sign up'
                div#admin_new_signup_roles
                  - Role.all.each do |role|
                    = check_box_tag 'signup[roles][]', role, true
                    | #{t "role.#{role}"} &nbsp;&nbsp;&nbsp;
          /- unless @raid.signups.empty?
            dt Edit Signups:
            dd#remove_signup
              table
                tr
                  th Signup
                  - if admin?
                    th Tags
                  th
                - @raid.signups.each do |signup|
                  tr
                    td = signup
                    - if admin?
                      = render :partial => 'tags', :locals => {:signup => signup}
                    td = link_to 'Remove Signup', raid_signup_url(@raid, signup), :confirm => "Are you sure you want to remove #{signup} from this raid?", :class => 'tiny', :method => :delete
          /- unless @raid.logs.empty?
            dt Logs
            dd#logs
              table
                tr
                  th Account
                  th Character
                  th Loot
                  th Source
                  th Messages
                  th Time
                - @raid.logs.each_with_index do |log, index|
                  tr.log id=dom_id(log) class=(index > 9 ? 'hidden' : 'shown')
                    td = link_to log.account, account_path(log.account)
                    td
                      - if log.character
                        = link_to render(:partial => 'shared/character', :object => log.character), account_path(log.character.account, :anchor => "character_#{log.character.id}")
                    td = link_to log.account, account_path(log.account)
                    td
                      - if log.character
                        = link_to render(:partial => 'shared/character', :object => log.character), account_path(log.character.account, :anchor => "character_#{log.character.id}")
                    td = link_to log.loot.item_name, log.loot.item_url, :class => 'loot' if log.loot
                    td = log.source
                    td = log.message
                    td = log.created_at.to_s(:raid_short)
        /dt Tag Chart
        /dd#tags
          p
            | Select the tag you want to view from this drop down. If you have no
            | tags defined then the only option will be "Seated". Signups are
            | totaled separately on the right. If an account was signed up for a
            | raid than the background of the box will be highlighted with light
            | grey.
          select#tag_select(name="tag_select")
            option(value="seated") Seated
            - @tags.each do |tag|
              option(value="#{tag.slug}")= tag
            table
              thead
                tr
                  th rowspan="2" Account
                  th rowspan="2" Character
                  - @recent_raids.each do |raid|
                    th = raid.name
                  th rowspan="2" Total
                  th.header rowspan="2" Sign Ups
                tr
                  - @recent_raids.each do |raid|
                    th.header = raid.date.strftime('%m-%d-%Y')
              tbody
                - @raid.signups.group_by { |signup| signup.character.account }.each do |account, signups|
                  tr.account
                    td rowspan=signups.size = link_to account, account_path(account)
                    td.char = link_to(render(:partial => 'shared/character', :object => signups.first.character), account_path(signups.first.character.account, :anchor => "character_#{signups.first.character.id}"))
                  - @recent_raids.each do |raid|
                    td rowspan=signups.size class=("signed_up" if account.signed_up_for(raid))
                      span.stat.seated = "X" if account.seated_for(raid)
                      - @tags.each do |tag|
                        span.stat class=tag.slug = "X" if not account.raider_tags.for_raid(raid).empty?
                  td.total rowspan=signups.size
                    span.stat.total.seated = @recent_raids.inject(0) { |total, raid| total + (account.seated_for(raid) ? 1 : 0) }
                    span.stat.total.signed_up = @recent_raids.inject(0) { |total, raid| total + (account.signed_up_for(raid) ? 1 : 0) }
                    - @tags.each do |tag|
                      span.stat.total class=tag.slug = @recent_raids.inject(0) { |total, raid| total + (account.raider_tags.for_raid(raid).empty? ? 0 : 1) }
                  td.stat.total rowspan=signups.size = @recent_raids.inject(0) { |total, raid| total + (account.signed_up_for(raid) ? 1 : 0) }
                - signups[1..-1].each do |signup|
                  tr
                    td.char = link_to(render(:partial => 'shared/character', :object => signup.character), account_path(signup.character.account, :anchor => "character_#{signup.character.id}"))
      - else
        dt
        dd
          p This raid is not yet finalized. You can edit your signups above but until the raid is finalize you can not see the current signup list.
          p Please use the note field to indicate any special requests. "Only if there is room", "Prefer Healing" and the like.
          p We will try to get raids finalize at least 48 hours before they start. Sooner if plenty of people sign up in time.

javascript:
  var raid_id = <%= @raid.id %>;

  $(document).ready(function() {
    make_signup('dd#slots dd.signup, dl#waiting_list dd.signup');
    make_slot('dl#waiting_list', '*');

    #{slots(@raid)}
  });