config/routes.rb
Lilyraid::Application.routes.draw do
  resources :lists
  resource :calendar
  resources :characters
  resources :accounts do
    member do
      post :add_to_list
      post :remove_from_list
    end

    resources :characters do
      member do
        get :roles
      end
    end
  end

  resources :raids do
    member do
      post :finalize
    end

    resources :signups do
      member do
        post :preferred
      end
    end

    resources :accounts do
      resources :raider_tags
    end

    resources :loots
    resources :locations
    resources :slots do
      collection do
        put :wait_list
      end
    end
  end

  namespace :admin do
    resources :characters
    resources :templates
    resources :instances
    resources :accounts do
      collection do
        post :rename
      end
    end
    resources :tags
    resources :guilds
  end

  match 'wowhead/:search' => 'loots#search', :as => 'wowhead'
  match 'roles/:id' => 'characters#roles'

  match 'login' => 'login#index', :as => 'login', :via => :get
  match 'login' => 'login#create', :as => 'login_post', :via => :post
  match 'logout' => 'login#logout', :as => 'logout', :via => :get

  root :to => 'raids#index'
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :account

  has_many :signups, :dependent => :nullify
  has_many :raids, :through => :signups

  has_many :loots, :dependent => :nullify
  has_many :logs, :dependent => :destroy

  validates :name, :uniqueness => { :scope => :realm }
  validates :account_id, :presence => true
  validates :race_id, :presence => true
  validates :cclass_id, :presence => true

  before_destroy :can_delete?

  default_scope :order => 'level desc, name'

  scope :active, { :conditions => { :inactive => false } }
  scope :inactive, { :conditions => { :inactive => true } }

  scope :seated_in, lambda { |raid| {
      :include => { :signups => :slot },
      :conditions => ["signups.raid_id = ? and slots.signup_id = signups.id", raid.id] } }

  scope :not_signed_up_for, lambda { |raid| {
      :conditions => ["not exists (select 1
                                     from signups
                                    where raid_id = ?
                                      and character_id = characters.id)", raid.id] } }

  scope :in_loot_list, {
    :include => { :account => :list_positions },
    :conditions => "list_positions.id is not null",
    :order => "list_positions.position" }

  scope :not_in_loot_list, {
    :conditions => ["not exists (select 1
                                   from list_positions lp
                                  where lp.account_id = characters.account_id
                                    and lp.list_id = ?)", List.first ? List.first.id : 0] }

  @@sides = { 
    1 => 'alliance',
    2 => 'horde',
    3 => 'alliance',
    4 => 'alliance',
    5 => 'horde',
    6 => 'horde',
    7 => 'alliance',
    8 => 'horde',
    9 => 'horde',
    10 => 'horde',
    11 => 'alliance',
    22 => 'alliance' }
  @@sides.default = 'neutral'

  def <=>(other)
    [other.level, name] <=> [level, other.name]
  end

  def to_s
    self.name
  end

  def name_with_level
    "#{name} (#{level})"
  end

  def name_with_level_and_account
    "#{name} (#{level}-#{account.name})"
  end

  def name_with_account
    "#{name} (#{account.name})"
  end

  def can_delete?
    raids.empty?
  end

  def is_alliance?
    self.side == 'alliance'
  end

  def is_horde?
    self.side == 'horde'
  end

  def side
    @@sides[self.race_id].titlecase
  end

  def pretty_realm
    Realms.name(self.realm)
  end

  def update_from_armory!(realm = self.realm, character = self.name)
    data = API.character(realm, character, 'fields' => 'guild')

    if data
      self.realm = realm
      self.name = data['name']
      self.cclass_id = data['class']
      self.race_id = data['race']
      self.level = data['level']
      self.guild = data['guild'].try(:[], 'name')
      self.thumbnail = data['thumbnail']
      self.save
    end

    # Check for new guilds
    guild = Guild.named(self.guild)

    if guild.nil? and self.guild.present?
      guild = Guild.new(:name => self.guild, :realm => self.realm)
      guild.update_from_armory!
      Guild.add(guild)
    end

    self
  end

  def self.guilds
    Character.select('distinct guild').map(&:guild).compact
  end
end

app/controllers/admin/characters_controller.rb
class Admin::CharactersController < ApplicationController
  def create
    @account = Account.find(params[:character][:account_id])

    authorize! :edit, @account
    @character = Character.new(params[:character])
    @character.update_from_armory!

    redirect_to admin_accounts_url
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter(:load_account, :except => [:roles, :index])
  before_filter(:load_character, :only => [:destroy, :edit, :update])

  def index
    authorize! :read, Character
    @characters = Character.order(:guild, :officer, :name).all
  end

  def new
    authorize! :edit, @account
    @character = @account.characters.build(:realm => CONFIG[:realm])
  end

  def create
    authorize! :edit, @account
    @character = @account.characters.build(params[:character])
    @character.update_from_armory!

    respond_to do |format|
      format.html { redirect_to account_url(@account) }
      format.js
    end
  end

  def edit
    authorize! :update, @character

    respond_to do |format|
      format.html
      format.js { render :template => false }
    end
  end

  def update
    authorize! :update, @character
    @character.attributes = params[:character]
    @character.update_from_armory!

    respond_to do |format|
      format.html { redirect_to account_url(@account) }
      format.js
    end
  end

  def destroy
    authorize! :destroy, @character
    @character.destroy

    respond_to do |format|
      format.html { redirect_to account_url(@account) }
      format.js { render :template => false }
    end
  end

  def roles
    @character = Character.find(params[:id])

    respond_to do |format|
      format.js { render(:partial => "raids/role", :collection => @character.cclass.roles) }
    end
  end

  private

  def load_account
    @account = Account.find(params[:account_id])
  end

  def load_character
    @character = @account.characters.find(params[:id])
  end
end

app/helpers/admin/characters_helper.rb
module Admin::CharactersHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
  def character_link(character)
    link_to character.name, "http://#{CONFIG[:region]}.battle.net/wow/character/#{URI.escape(CONFIG[:realm])}/#{URI.escape(character.name)}/simple"
  end

  def guild_link(character)
    if character.guild.present?
      link_to character.guild, "http://#{CONFIG[:region]}.battle.net/wow/guild/#{URI.escape(CONFIG[:realm])}/#{URI.escape(character.guild)}/?character=#{URI.escape(character.name)}"
    end
  end

  def character_image_url(character)
    "http://#{CONFIG[:region]}.battle.net/static-render/#{CONFIG[:region]}/#{character.thumbnail}"
  end
end

app/views/characters/_character.html.slim
.character id=dom_id(character) class=('inactive' if character.inactive?)
  .portrait
    .avatar
      = image_tag character_image_url(character)
    - if Guild.named(character.guild)
      .guild
        .bg &nbsp;
        = guild_icon(Guild.named(character.guild))
  .info
      h3 = character_link(character)
      - if character.guild.present?
        p = guild_link(character)
      p #{character.level} #{t("race.#{character.race_id}") if character.race_id} #{render(:partial => "shared/cclass", :object => character.cclass_id) if character.cclass_id}
      p = character.pretty_realm
      - if can? :edit, character
        ul.actions
          li = link_to 'Edit', edit_account_character_path(character.account, character)
          li = link_to 'Reload', account_character_url(character.account, character), :method => :put, :class => 'update'
          - if character.raids.empty?
            li = link_to 'Delete', account_character_url(character.account, character), :confirm => 'Are you sure?', :method => :delete, :class => 'delete'
          - if character.inactive?
            li.inactive Inactive

app/views/characters/_form.html.slim
- if character.new_record?
  h3 New Character
- else
  h3 Edit Character
= simple_form_for([character.account, character]) do |f|
  = f.input :name
  = f.input :realm, :collection => Realms.all.map {|s,n| [n,s]}
  - unless @character.new_record?
    = f.input :inactive
    p.note
      | If you mark a character inactive they won't show up when signing up
      | for raids. You can mark them active again at any time.
  .submit
    = f.submit 'Save'

app/views/characters/_roles.html.slim
- character.cclass.roles.each do |role|
  = check_box_tag "signup[role_ids][]", role.id, true
  = role.name
  | &nbsp; &nbsp; &nbsp;

app/views/characters/destroy.js.erb
<% if @character %>
$('#character_<%= @character.id %>').fadeOut();
<% end %>

app/views/characters/edit.html.slim
= render :partial => "characters/form", :locals => { :character => @character }

app/views/characters/edit.js.erb
$('#character_<%= @character.id %>').replaceWith("<%= escape_javascript(render(:partial => "characters/form",
  :locals => {
    :character => @character,
    :instances => @instances,
    :races => @races,
    :cclasses => @cclasses
  })) %>");

app/views/characters/index.html.slim
h1 Member List
.members
  - @characters.group_by(&:guild).each do |guild, members|
    .guild
      .icon = guild_icon(Guild.named(guild)) if guild
      .list
        h2 = guild || 'No Guild'
        - members.group_by(&:officer).each do |officer, characters|
          - if guild
            h3 = officer ? 'Officers' : 'Members'
          ul
            - characters.each do |character|
              li = link_to(render(:partial => "shared/character", :object => character), account_path(character.account_id))

app/views/characters/new.html.slim
- if flash[:notice]
  = flash[:notice]
= render :partial => "characters/form", :locals => { :character => @character }

app/views/characters/update.js.erb
$('#character_<%= @character.id %>').replaceWith('<%= escape_javascript(render(:partial => @character)) %>');