config/routes.rb
Lilyraid::Application.routes.draw do
  resources :lists
  resource :calendar
  resources :characters
  resources :accounts do
    member do
      post :add_to_list
      post :remove_from_list
    end

    resources :characters do
      member do
        get :roles
      end
    end
  end

  resources :raids do
    member do
      post :finalize
    end

    resources :signups do
      member do
        post :preferred
      end
    end

    resources :accounts do
      resources :raider_tags
    end

    resources :loots
    resources :locations
    resources :slots do
      collection do
        put :wait_list
      end
    end
  end

  namespace :admin do
    resources :characters
    resources :templates
    resources :instances
    resources :accounts do
      collection do
        post :rename
      end
    end
    resources :tags
    resources :guilds
  end

  match 'wowhead/:search' => 'loots#search', :as => 'wowhead'
  match 'roles/:id' => 'characters#roles'

  match 'login' => 'login#index', :as => 'login', :via => :get
  match 'login' => 'login#create', :as => 'login_post', :via => :post
  match 'logout' => 'login#logout', :as => 'logout', :via => :get

  root :to => 'raids#index'
end

app/models/raid.rb
class Raid < ActiveRecord::Base
  belongs_to :account
  belongs_to :instance
  belongs_to :list

  has_many :raider_tags
  has_many :tags, :through => :raider_tags

  has_many :locations
  accepts_nested_attributes_for(:locations, :allow_destroy => true,
                                :reject_if => proc { |attr|
                                  attr['instance_id'].blank?
                                })
  has_many :instances, :through => :locations
  has_many :loots, :through => :locations

  before_save :apply_number_of_slots

  has_many :slots, :dependent => :destroy

  has_many :signups, :dependent => :destroy
  has_many :characters, :through => :signups

  has_many :logs

  scope :past, lambda { where('raids.date < ?', Date.today) }
  scope :last_month, lambda { where('raids.date >= ?', Date.today - 1.month) }
  scope :last_three_months, lambda { where('raids.date >= ?', Date.today - 3.months) }
  scope :in_instance, lambda { |instance| where(:instance_id => instance) }

  Inf = 1/0.0

  def to_s
    self.name
  end

  # Validation
  validates_presence_of :name

  def started?
    Time.now > self.date
  end

  def number_of_slots
    self.slots.size || 10
  end

  def number_of_slots=(num)
    @number_of_slots = case num
                       when String
                         num.to_i
                       else
                         num
                       end
  end

  def date=(date)
    case date
    when String
      write_attribute(:date, Time.parse(date))
    else
      write_attribute(:date, date)
    end
  end        

  def confirmed_characters
    slots.map do |slot|
      if slot.signup
        slot.signup.character
      end
    end.compact
  end

  def accounts
    slots.map do |slot|
      if slot.signup
        slot.signup.character.account
      end
    end.compact
  end

  def character_in_raid(character)
    confirmed_characters.member?(character)
  end

  def waiting_list_by_account
    waiting_list.inject([]) do |list, signup|
      if list.empty?
        [[signup]]
      elsif list.last.first.character.account_id == signup.character.account_id
        list.last << signup
        list
      else
        list << [signup]
      end
    end
  end

  def is_open
    return true

    slots.each do |slot|
      if !slot.closed
        return true
      end
    end

    return false
  end

  def signups_from(account)
    signups.select do |signup|
      signup.character.account == account
    end
  end

  def remove_character(char)
    # Delete the signup_slot_types and signup row
    signup = self.signups.where(:character_id => char).first

    if signup
      date = signup.date
      # Destroy signups, this opens the slots up as well
      Signup.destroy(signup.id)

      # Redo the raid if raid
      resignup(date) unless locked

      return true
    else
      return false
    end
  end

  def find_character(char)
    self.slots.includes(:signup).where(:character_id => char).first
  end

  def resignup(date)
    signups = Signup.where('date >= ?', date).all

    # Delete all slots that are tied to signsup past this date
    signups.each do |signup|
      signup.clear_slots
    end

    # redo all signups that occur on or past this date
    signups.each do |signup|
      place_character(signup)
    end
  end

  def waiting_list
    accounts = slots.map { |slot| slot.signup }.compact.map { |signup| signup.character.account }

    signups.select do |signup|
      !accounts.member?(signup.character.account)
    end
  end

  def place_character(signup)
    self.slots.where('signup_id is null and closed = ?', false).order('cclass_id desc, slot_type_id desc').all.each do |slot|
      if slot.accept_char(signup)
        # This slow will accept this character
        slot.signup = signup
        slot.save
        break;
      end
    end
  end

  def add_waiting_list
    waiting_list.each do |signup|
      place_character(signup)
    end
  end

  def groups
    slots.each_slice(5)
  end

  def can_be_deleted?
    loots.size == 0
  end

  # Used for templates
  def template_id=(template_id)
    return if template_id.blank?

    # Number of slots that this raid has
    number_in_raid = self.slots.count

    # Apply a raid template to this raid
    template = Template.find(template_id)
    number_in_template = template.slots.count

    # Remove some slots from this raid
    self.slots.all[number_in_template..-1].map(&:destroy) if number_in_template < number_in_raid

    template.slots.each_with_index do |slot, index|
      if index < number_in_raid
        raid_slot = self.slots[index]

        # We only care if these slots are different
        if raid_slot != slot
          signup = raid_slot.signup
          raid_slot.update_attributes(slot.attributes)
          raid_slot.raid = self
          raid_slot.template = nil

          # Remove character if there is one that doesn't fit into the template
          if signup and raid_slot.accept(signup)
            raid_slot.signup = signup
          end
        end
      else
        # Easy, just create the new one
        self.slots.build(slot.attributes).template = nil
      end
    end
  end

  def uid
    "raid_#{self.id}@raids.dota-guild.com"
  end

  def word_date
    days = self.date.to_date - Date.today

    case days
    when -Inf..-1
      "In the past"
    when 0
      "Today"
    when 1
      "Tomorrow"
    when 2..days_left_in_week
      "This #{day_name(self.date)}"
    when (days_left_in_week + 1)..(days_left_in_week + 7)
      "Next #{day_name(self.date)}"
    when (days_left_in_week + 8)..days_left_in_month
      "Later this month"
    when (days_left_in_month + 1)..days_left_in_two_months
      "Next month"
    when (days_left_in_two_months + 1)..days_left_in_year
      "Later this year"
    else
      "In the future"
    end
  end

  private

  def day_name(date)
    date.strftime("%A")
  end

  def days_left_in_week
    Date.today.end_of_week - Date.today
  end

  def days_left_in_month
    Date.today.end_of_month - Date.today
  end

  def days_left_in_two_months
    (Date.today + 1.month).end_of_month - Date.today
  end

  def days_left_in_year
    Date.today.end_of_year - Date.today
  end

  def apply_number_of_slots
    # If we have a number of slots set, then apply them
    if @number_of_slots

      # Get the current number of slots
      number_in_raid = self.slots.count

      self.slots.all[@number_of_slots..-1].map(&:destroy) if @number_of_slots < number_in_raid

      (@number_of_slots - number_in_raid).times do
        self.slots.build(:roles => Role::ALL)
      end
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_filter :authorize, :only => [:new, :create]

  def index
    authorize! :read, Account
    @admins = Account.admins
    @members = Account.members
  end

  def show
    @account = Account.find(params[:id])
    authorize! :read, @account

    if can? :update, @account
      @character = Character.new(:account => @account)
    end
  end

  def new
    @account = Account.new(:name => params[:name])
    authorize! :create, Account
  end

  def create
    @account = Account.new(params[:account])
    authorize! :create, Account

    if params[:creation_password] == CONFIG[:account_creation_password]
      if @account.save
        redirect_to account_url(@account)
      else
        render :action => "new"
      end
    else
      @account.errors.add(:base, 'Wrong account creation password')
      render :action => "new"
    end
  end

  def add_to_list
    @list = List.first

    @account = Account.find(params[:id])
    @lp = @list.add_to_end(@account)

    @raid = Raid.find(params[:raid_id])

    respond_to do |format|
      format.html { redirect_to @raid }
      format.js { render :template => false }
    end
  end

  def remove_from_list
    @list = List.first
    @account = Account.find(params[:id])

    lp = @list.find(@account)
    lp.destroy

    redirect_to lists_url
  end

  def edit
    @account = Account.find(params[:id],
                            :include => { :characters => [:raids,
                                                          :signups,
                                                          :account] } )
    authorize! :update, @account

    if @current_account == @account || @current_account.admin
      respond_to do |format|
        format.html
        format.js { render :layout => false }
      end
    else
      respond_to do |format|
        format.html { redirect_to account_url(@account) }
        format.js do
          render :js => "window.location = '#{account_url(@account)}';"
        end
      end
    end
  end

  def update
    @account = Account.find(params[:id],
                            :include => { :characters => [:raids,
                                                          :signups,
                                                          :account] } )
    authorize! :update, @account

    if @account.update_attributes(params[:account])
      respond_to do |format|
        format.html { redirect_to account_url(@account) }
        format.js { render :layout => false }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.js
      end
    end
  end
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < ApplicationController
  before_filter :require_admin

  def index
    authorize! :update, Account
    @accounts = Account.order('name').all
    @account = Account.new
    @character = Character.new
    @deletable = Account.order('name').all.select do |account|
      account.can_delete?
    end
  end

  def create
    authorize! :create, Account

    @account = Account.new(params[:account])
    if @account.save
      redirect_to admin_accounts_url
    else
      @accounts = Account.order('name').all
      @character = Character.new
      @deletable = Account.order('name').all.select do |account|
        account.can_delete?
      end

      render :action => "index"
    end
  end

  def rename
    Account.update(params[:id], params[:account])

    redirect_to admin_accounts_url
  end

  def destroy
    @account = Account.find(params[:id])
    authorize! :destroy, @account

    @account.destroy

    redirect_to accounts_url
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def lj_link(account)
    "http://#{account.lj_account}.livejournal.com/"
  end
end

app/helpers/admin/accounts_helper.rb
module Admin::AccountsHelper
end

app/views/accounts/_account.html.slim
div.account id=dom_id(account)
  h3 = account.name
  ul.actions
    - if can? :update, account
      li = link_to 'Edit', edit_account_url(account), :class => 'edit'
    - if can? :destroy, account and account.can_delete?
      li = link_to 'Delete', admin_account_url(account), :method => :delete, :class => 'delete'
  dl
    - if account.age.present?
      dt Age:
      dd = account.age
    - if account.location.present?
      dt Location:
      dd = account.location
    - if account.lj_account.present?
      dt LJ:
      dd = link_to account.lj_account, lj_link(account), :class => "lj"
    - if account.bio.present?
      dt Bio:
      dd = account.bio

app/views/accounts/_characters.html.slim
- account = characters
tr
  td = link_to(account.name, account_url(account))
    - account.active_characters.each do |character|
      td
        = link_to(render(:partial => "shared/character", :object => character), "#{account_url(account)}##{dom_id(character)}") %>&nbsp;<%= character.level

app/views/accounts/_edit_character.html.slim
- character = edit_character
div id="character_#{character.id}" style="padding-bottom: 50px;"
  = form_for(:character, character, :remote => true \
             :url => { :action => "update_character", \
                       :id => character.id }, \
             :method => :post, \
             :loading => update_page do |page| \
                 page["character_#{character.id}_submit"].value = "Saving ..." \
                 page["character_#{character.id}_submit"].disable \
             end ) do |f|
    table.info
      tr
        th Name:
        td = f.text_field :name
      tr
        th Level:
        td = f.text_field :level, :size => 5
      tr
        th Race:
        td = f.collection_select(:race_id, races, :id, :to_s)
      tr
        th Class:
        td = f.collection_select(:cclass_id, cclasses, :id, :to_s)
      tr
        th Guild:
        td = f.text_field :guild
      tr
        th Keyed:
        td
          - @key_instances.each do |instance|
            = check_box_tag "character[instance_ids][]", instance.id, character.instances.member?(instance)
            = instance
            br
      tr
        th
        td
          = submit_tag "Save", :id => "character_#{character.id}_submit"
          = link_to("Delete", { :action => "delete_character", :id => character.id }, :remote => true, \
                    :confirm => "Are you sure you want to delete #{character.name}?")

app/views/accounts/_form.html.slim
div.account id=dom_id(account)
  - if account.new_record?
    h1 New Account
  - else
    h1 Edit Account
  = simple_form_for account do |f|
    = f.input :lj_account
    p.note
      | This is just your livejournal username. For example, if your journal
      | exists at "ayashi.livejournal.com", you should only enter "ayashi"
      | here.
    = f.input :age
    = f.input :location
    = f.input :bio, :input_html => { :rows => 8 }
    - if CONFIG[:auth] == 'login'
      = f.input :change_password, :as => :password, :label => 'New Password'
      = f.input :password_confirmation, :as => :password, :label => 'Confirmation'
    .submit
      = f.submit 'Save'

app/views/accounts/add_to_list.js.erb
// Remove Add to List item
$('#add_to_loot_list dd.account_<%= @account.id %>').fadeOut(1000, function () {
    $(this).remove();
});

if($('#add_to_loot_list dd:visible:not(.account_<%= @account.id %>)').size() < 1) {
    $('#add_to_loot_list').fadeOut();
}

// Add new loot list item
$('#loot_list').append('<%= escape_javascript(render(:partial => "raids/position", :locals => { :position => @lp, :raid => @raid, :hide => true })) %>');
$('#loot_list dd.account_<%= @account.id %>').slideDown();

app/views/accounts/edit.html.slim
= render :partial => "accounts/form", :locals => { :account => @account }

app/views/accounts/edit.js.erb
$('#account_<%= @account.id %>')
    .replaceWith('<%= escape_javascript(render(:partial => "accounts/form", :locals => { :account => @account })) %>');

app/views/accounts/index.html.slim
div.raid
  h3 Accounts
  - unless @admins.empty?
    h4 Admins
    dl
      - @admins.each do |account|
        dt = link_to account.name, account_url(account)
        - account.characters.each do |character|
          dd
            = link_to(render(:partial => "shared/character", :object => character), "#{account_url(account)}#character_#{character.id}")
  - unless @members.empty?
    h4 Normal Accounts
    dl
      - @members.each do |account|
        dt = link_to account.name, account_url(account)
        - account.characters.each do |character|
          dd = render :partial => "shared/character", :object => character

app/views/accounts/new.html.slim
div.raid
  h3 New Account
  = errors_for @account
  p You can create a new account by filling out the info below. If you already have an account you can #{link_to "login", login_url}.
  = form_for @account do |f|
    dl
      dt Name:
      dd = f.text_field :name
      dt Password:
      dd = f.password_field :change_password
      dt Confirm:
      dd = f.password_field :password_confirmation
    p To create an account you need to get a password from your guild master:
    dl
      dt
      dd = password_field_tag :creation_password
      dt
      dd = submit_tag "Create"

app/views/accounts/show.html.slim
h1 = @account.name
.account
  .characters
    h2 Characters
    = render :partial => "characters/character", :collection => @account.characters
  .info
    h2 Account Info
    dl
      - if @account.age.present?
        dt Age:
        dd = @account.age
      - if @account.location.present?
        dt Location:
        dd = @account.location
      - if @account.lj_account.present?
        dt LJ:
        dd = link_to @account.lj_account, lj_link(@account), :class => "lj"
    - if @account.bio.present?
      p = @account.bio
    ul.actions
      - if can? :update, @account
        li = link_to 'Edit', edit_account_url(@account), :class => 'edit'
      - if can? :destroy, @account and @account.can_delete?
        li = link_to 'Delete', admin_account_url(@account), :method => :delete, :class => 'delete'
    - if can? :update, @account
      = render :partial => 'characters/form', :locals => { :character => @character }

app/views/accounts/update.js.erb
<% if @account.valid? %>
  $('#account_<%= @account.id %>')
    .replaceWith('<%= escape_javascript(render(:partial => "accounts/account", :object => @account)) %>');
<% else %>
  $('#account_<%= @account.id %>')
    .replaceWith('<%= escape_javascript(render(:partial => "accounts/form", :locals => { :account => @account })) %>');
<% end %>